### ISSUE TITLE
[Bug] Wallpapers get replaced by last set wallpaper or by default wallpaper in certain scenarios

### ISSUE THREAD

**Issue by abdu27th** [pop-os/cosmic-settings#1265]
### Summary
The wallpaper changes to either the last set wallpaper or to the default wallpaper in certain scenarios. I listed two of them below but I'm not sure if those are the only ones. The wallpaper preview at the top of the settings page change to black in both cases. 

---

#### Scenario 1:
1. Set a wallpaper from the default "Wallpapers" folder (let's call it 1)
2. Re-launch COSMIC Settings
3. Set to another wallpaper (let's call it 2)
4. Change to a custom wallpapers folder and then back to the default
5. Observe the wallpaper reverting from wallpaper 2 to wallpaper 1

#### Scenario 2:
1. Set a wallpaper from a custom folder (let's call it 1)
2. Re-launch COSMIC Settings
3. Change to the default "Wallpapers" folder
4. Re-launch COSMIC Settings
5. Observe the wallpaper changing from wallpaper 1 to the default COSMIC wallpaper

Note: Going back to the folder of wallpaper 1 before closing COSMIC Settings will set it back again in this scenario.

### Expected Behavior
The wallpaper only changes when another one is set regardless of which folder is open or what wallpaper was set previously.

### Actual Behavior
The wallpaper changes unexpectedly in certain scenarios.

### Environment
- OS: Pop!_OS 24.04 LTS

**Comment by Doods0** [comment]
As-salamu alaykum.

Can you reproduce this on master? I think I fixed it in https://github.com/pop-os/cosmic-settings/pull/1256, if you can't, then please close the issue.

**Comment by abdu27th** [comment]
I’m not sure how to check it on master. I’m on the latest repo release.

**Comment by Doods0** [comment]
Oh! I managed to reproduce it on master, sorry for my failure.

I'm still looking into your other issue, though, so I will be busy for a bit. (hint: It's due to a band-aid fix)

**Comment by KodeBarista** [comment]
Both scenarios are still reproducible. Also the wallpaper only flicker when default wallpaper folder is selected in Setting with Appearance as current page.

Edit: Scenario 2 can longer be reproduced.
